import Head from 'next/head'
import Header from './components/Header'
import Image from 'next/image'
import Audioplayer from './components/Audioplayer'



export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>911</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sunflower.ico" />
      </Head>
<div className='  '>
<div className='flex min-h-screen  '>
  {/* Partie marron  */}
        <div className='bg-theme p-10 w-full text-white flex-1'>
          <p className=''>Subscribe </p>
          <p className='lg:text-9xl  font-bold lg:absolute ml-48  '>TYLER <br/> THE CREATOR </p>
          <div className='hidden lg:block absolute ml-[26rem] '>
          <Image
          src={'/tylerpng.png'}
          alt="Picture of the author"
          width="701px"
          height="682px"  
          />
        </div>
        {/*Latest  */}
        <div className='relative lg:mt-96 opacity-60 lg:mx-40'>
          Latest
        </div>
        <div className='mx-10 flex mb-4 items-center'>
            <Audioplayer sourceFile="/LEMONHEAD.mp3" title="LEMONHEAD"/>
            <Audioplayer sourceFile="/MASSA.mp3" title="MASSA"/>
        </div>
        </div>
        {/* Partie bleue */}
        <div className='lg:w-1/3 justify-end flex text-xs bg-secondary text-white'>
          <a className='mt-10 m-8' href='#'>instagram </a>
          <a className='mt-10 m-8' href='#'>twitter </a>
          <a className='mt-10 m-8' href='#'>tumblr </a>
        </div>
      </div>
      <div className=' '>
      <Header/> 
      </div>
      
</div>
      </div>
  )
}
